import numba
import numpy as np
import pygame as pg
import moderngl as mgl
import math
from pyglm import glm

#RESOLUTION
WIN_RES = glm.vec2(1600, 900)

#OPENGL SETTINGS
MAJOR_VER, MINOR_VER = 3, 3
DEPTH_SIZE = 24
NUM_SAMPLES = 1  # antialiasing

#RAY_CASTER
MAX_RAY_DISTANCE = 8

#CHUNK
CHUNK_SIZE = 32
P_CHUNK_SIZE = CHUNK_SIZE + 2
H_CHUNK_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOL = CHUNK_AREA * CHUNK_SIZE
H_CHUNK_VOL = CHUNK_VOL // 2
CHUNK_SPHERE_RADIUS = H_CHUNK_SIZE * math.sqrt(3)

#WORLD
WORLD_W = WORLD_D = 20
WORLD_H = 3
WORLD_AREA = WORLD_W * WORLD_D
WORLD_VOL = WORLD_AREA * WORLD_H

#WORLD GENERATION
SEED = 16

#WORLD_CENTER
WORLD_CENTER_XZ = WORLD_W * H_CHUNK_SIZE
WORLD_CENTER_Y = WORLD_H * H_CHUNK_SIZE

#CAMERA
ASPECT_RATIO = WIN_RES.x / WIN_RES.y
FOV_DEG = 50
V_FOV = glm.radians(FOV_DEG)
H_V_SEC = glm.sec(V_FOV*0.5); H_V_TAN = glm.tan(V_FOV*0.5)
H_FOV = 2 * math.atan(math.tan(V_FOV * 0.5) * ASPECT_RATIO)
H_H_SEC = glm.sec(H_FOV*0.5); H_H_TAN = glm.tan(H_FOV*0.5)
NEAR = 0.1
FAR = 2000.0
PITCH_MAX = glm.radians(89)

#PLAYER
PLAYER_SPEED = 0.01
PLAYER_ROT_SPEED = 0.003
#PLAYER_POS = glm.vec3(1, 1, 1)
PLAYER_POS = glm.vec3(WORLD_CENTER_XZ, WORLD_H * CHUNK_SIZE, WORLD_CENTER_XZ)
MOUSE_SENSITIVITY = 0.002


BG_COLOR = glm.vec3(0.6, 0.8, 0.99)

#BLOCK IDS
WATER = 8
WOOD = 7
LEAVES = 6
SNOW = 5
STONE = 4
DIRT = 3
GRASS = 2
SAND = 1
EMPTY = 0

#TERRAIN LEVELS
SNOW_LEVEL = 54
STONE_LEVEL = 49
GRASS_LEVEL = 10
DIRT_LEVEL = 10
SAND_LEVEL = 7
WATER_LEVEL = 4

#TREE
TREE_HEIGHT = 7
MIN_TREE_WIDTH = 2
MAX_TREE_WIDTH = 4
TREE_WIDTH_RANGE = MAX_TREE_WIDTH - MIN_TREE_WIDTH
TREE_PROBABILITY = 0.01

#CLOUD
CLOUD_HEIGHT = WORLD_H * CHUNK_SIZE * 2
