import numba
import numpy as np
import pygame as pg
import moderngl as mgl
import glm
import math

# resolution
WIN_RES = glm.vec2(1600, 900)

#RAY_CASTER
MAX_RAY_DISTANCE = 5

#chunk
CHUNK_SIZE = 32
H_CHUNK_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOL = CHUNK_AREA * CHUNK_SIZE

#WORLD
WORLD_W = WORLD_D = 10
WORLD_H = 3
WORLD_AREA = WORLD_W * WORLD_D
WORLD_VOL = WORLD_AREA * WORLD_H

#WORLD_CENTER
WORLD_CENTER_XZ = WORLD_W * H_CHUNK_SIZE
WORLD_CENTER_Y = WORLD_H * H_CHUNK_SIZE

# camera 
ASPECT_RATIO = WIN_RES.x / WIN_RES.y
FOV_DEG = 50
V_FOV = glm.radians(FOV_DEG)
H_FOV = 2 * math.atan(math.tan(V_FOV * 0.5) * ASPECT_RATIO)
NEAR = 0.1
FAR = 2000.0
PITCH_MAX = glm.radians(89)

#player
PLAYER_SPEED = 0.005
PLAYER_ROT_SPEED = 0.003
PLAYER_POS = glm.vec3(WORLD_CENTER_XZ, WORLD_H * CHUNK_SIZE, WORLD_CENTER_XZ)
MOUSE_SENSITIVITY = 0.002


BG_COLOR = glm.vec3(0.1, 0.16, 0.25)

